### PR TITLE
get LUNC price from local pool

### LINKED ISSUE #767: [Testcase - Swap page] - Wrong price data for LUNC on frontier
The current exchange rate for LUNC is too high, if you swap $1 in ATOM or anything else for LUNC, you will get like $4 in LUNC
However, if you the same amount of LUNC swap back to another token, you will get the accurate price.
### Steps
1. https://frontier.osmosis.zone/
2. Try to swap $1 of ATOM or OSMO to LUNC

image
image

Swap back the same LUNC amount
image

### PR DESCRIPTION
**Pull request by JeremyParish69**
pool 561 OSMO/LUNC
resolves #767

### CODE REVIEW

File: packages/web/config/chain-infos.ts [hunk 1]
```diff
@@ -76,7 +76,8 @@ const chainInfos = (
           coinDenom: "LUNC",
           coinMinimalDenom: "uluna",
           coinDecimals: 6,
-          coinGeckoId: "terra-luna",
+          //coinGeckoId: "terra-luna",
+          coinGeckoId: "pool:uluna",
```
Comment (sunnya97) [inline packages/web/config/chain-infos.ts:80]: This is not going to get confused b/w LUNA vs LUNC right?

Comment (sunnya97) [reply packages/web/config/chain-infos.ts:80]: Is there a way to rename this pool to `pool:ulunc` by any chance?

Comment (JeremyParish69) [reply packages/web/config/chain-infos.ts]: yes, makes sense. Done
