### PR TITLE
Swap tool fixes

### LINKED ISSUE #1346: EVMOS decimals on the swap page break UI
image

### PR DESCRIPTION
**Pull request by jonator**
* Re-query pools in route when details are expanded (helps address #1274)
* Limit available balance to 8 decimals. Closes #1346 
* Only show swap route vis in home page, not in pool detail page

TODO
- [x] Max 8 decimals on token select

### CODE REVIEW

File: packages/web/components/trade-clipboard/index.tsx [hunk 1]
```diff
@@ -114,10 +114,28 @@ export const TradeClipboard: FunctionComponent<{
...
     // show details
-    const [showEstimateDetails, setShowEstimateDetails] = useState(false);
+    const [showEstimateDetails, _setShowEstimateDetails] = useState(false);
     const isEstimateDetailRelevant = !(
       tradeTokenInConfig.amount === "" || tradeTokenInConfig.amount === "0"
     );
+    const setShowEstimateDetails = useCallback(
+      (value: boolean) => {
+        // refresh current route's pools
+        if (value === true) {
```
Comment (JoseRFelix) [inline packages/web/components/trade-clipboard/index.tsx:124]:
```suggestion
        if (value) {
```

File: packages/web/components/trade-clipboard/index.tsx [hunk 2]
```diff
@@ -146,7 +164,7 @@ export const TradeClipboard: FunctionComponent<{
         fetchedRemainingPoolsRef.current = true;
         queries.osmosis?.queryGammPools.fetchRemainingPools();
       }
-    }, []);
+    }, [queries.osmosis?.queryGammPools]);
```
Comment (JoseRFelix) [inline packages/web/components/trade-clipboard/index.tsx:167]: @jonator What do you think of enabling `react-hooks/exhaustive-deps` eslint rule? If we want to opt out, we should add a eslint-disable comment. Exhaustive deps are important to avoid unexpected bugs coming from `useEffect`.

**Review by JoseRFelix — CHANGES_REQUESTED** [review]
Looks good, left some minor comments

File: packages/web/components/trade-clipboard/index.tsx (hunk 2 above)
Comment (jonator) [reply packages/web/components/trade-clipboard/index.tsx:167]: https://github.com/osmosis-labs/osmosis-frontend/issues/1349

I agree, @sehyunc pointed this out and will include it in his pools page redesign PR.

**Review by JoseRFelix — APPROVED** [review]
